# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c3246e999359597cd710faa74ef61485d19ee7a9cc94237c2324cb8ff13d64f0ff1286415e2eabd4464c2c9c7a6b8f9b1c076376177a8ee09800c2276f725e0c

test:
  secret_key_base: 21745c6aa721fd50fa74b8cc1d5b1fefb266d6259bbf520a18bc8c8501e174d57ad1af23159f1a47bfc194cdb4621bc54ae5938e37d03bc6c633539899d422aa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
